name: Personal website CI

on:
  push:
    branches:
      - testing 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -uses: actions/checkout@v2
      -name: Build the site
        run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"